# Generated by Django 5.0.3 on 2024-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('serie_turma', models.CharField(max_length=8)),
                ('data_matricula', models.DateField()),
            ],
        ),
    ]
